# Generated by Django 4.0.3 on 2022-03-28 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
