# Generated by Django 4.0.3 on 2022-04-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0003_phone_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='produced',
            field=models.DateField(null=True),
        ),
    ]
