# Generated by Django 4.0.3 on 2022-04-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0005_phone_author_phone_created_date_phone_edited_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
